# Generated by Django 4.2.2 on 2023-06-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naming_series', models.CharField(max_length=255)),
                ('running_number', models.IntegerField(default=1)),
            ],
        ),
    ]
