# Generated by Django 4.2.2 on 2023-06-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_salesorder_posting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='price_list_rate',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
